
start = expression

expression = "'" e:expression   { return ["quote", e]; }
  / a:atom " "*                 { return a; }
  /  "()" " "*                  { return []; }
  /  "(" list:elist ")" " "*    { return list; }
  /  " "+ e:expression          { return e; }

elist = first:expression rest:(expression)* 
                               { rest.splice(0, 0, first); return rest; }

atom = chars:validchar+        { return chars.join(""); }

validchar = [0-9a-zA-Z_?!+-=@#$%^&*/.]